lang: "zh_cn"

disabled-jobs:
  - test

lobbies:
  hub:
    location: [ 0, 100, 0 ]
    range:
      from: [ 100, 100 ]
      to: [ -100, -100 ]
    entry:
      time: 3000 #ms
      from: [9, 103, 1]
      to: [11, 100, -1]

  death:
    location: [ -500, 100, -500 ]
    range:
      from: [ -600, -600 ]
      to: [ -400, -400 ]

game:
  disabled-modes:
    - example_mode

  cooldown:
    enable: true
    factor: 1

  regeneration:
    enable: true
    health-per-regen: 1
    per-regen-time: 1

  mutation:
    enable: true
    time: # support static number / random range (inclusive)
      - 900       # gap
      - [ 60, 180 ] # mutation time
    tps: [ 10, 40 ]

  battle:
    single-game-time: 600
    respawn-time: 10
    leave-in-game-time: 5

    max-team: 4
    team-auto-balancing: true
    force-balancing: false

  steal:
    min-player-to-start: 2
    prepare-time: 30

    total-round: 10
    time-per-round: 10

ui:
  lobby:
    job-select-mode: hotbar
    jobs-per-page: 5
